// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYNsaO2wXs9eR2ha9Emx_GAoQucUvIWHA',
    appId: '1:457703051615:web:881f481f2e7a9bc502e6ea',
    messagingSenderId: '457703051615',
    projectId: 'krushidava-db',
    authDomain: 'krushidava-db.firebaseapp.com',
    storageBucket: 'krushidava-db.firebasestorage.app',
    measurementId: 'G-SYW6MNMN0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVM9fhw395o_g02N0XITL0Si5RHw9YBtA',
    appId: '1:457703051615:android:ea8d2e0498d30d5b02e6ea',
    messagingSenderId: '457703051615',
    projectId: 'krushidava-db',
    storageBucket: 'krushidava-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqHyPNu6XnGJrDsWtVN6OXmniU0E3gH-0',
    appId: '1:457703051615:ios:346d18eb9dae20a202e6ea',
    messagingSenderId: '457703051615',
    projectId: 'krushidava-db',
    storageBucket: 'krushidava-db.firebasestorage.app',
    iosBundleId: 'com.example.krushidava',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqHyPNu6XnGJrDsWtVN6OXmniU0E3gH-0',
    appId: '1:457703051615:ios:346d18eb9dae20a202e6ea',
    messagingSenderId: '457703051615',
    projectId: 'krushidava-db',
    storageBucket: 'krushidava-db.firebasestorage.app',
    iosBundleId: 'com.example.krushidava',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYNsaO2wXs9eR2ha9Emx_GAoQucUvIWHA',
    appId: '1:457703051615:web:8583efa0dc52a79402e6ea',
    messagingSenderId: '457703051615',
    projectId: 'krushidava-db',
    authDomain: 'krushidava-db.firebaseapp.com',
    storageBucket: 'krushidava-db.firebasestorage.app',
    measurementId: 'G-Z2TQ2X2MPN',
  );
}
